### ISSUE TITLE
How to generate both html_document and github_document

### ISSUE THREAD

**Issue by zjbthomas** [STAT545-UBC/Discussion-Internal#30]
I want to ask how to generate html_document and github_document at the same time.

I specify this in the YAML:

output:
  github_document: default
  html_document: default

But it only generates the github_document (.md).

If I use the following one, the generated MD file cannot be correctly rendered on GitHub.
output:
  html_document:
    keep_md: true

Thank you.

**Comment by vincenzocoia** [comment]
Not sure what you mean by "cannot be correctly rendered on GitHub" -- it should be.

**Comment by zjbthomas** [comment]
@vincenzocoia, @rasiimwe

Thanks for your responses.

My opinion is that the MD file generated by using `github_document` and `keep_md` is different.

One difference I notice is that knitr::kable() is not correctly rendered as a table when using `keep_md`, but with `github_document` it is fine.

However, I cannot find a way to generate `github_document` and HTML at the same time.

**Comment by zhamadeh** [comment]
@zjbthomas @vincenzocoia 

I just realized I was having the same problem. My .Rmd file was being rendered as a HTML but not as an .MD and turns out I had made a change to my knitr code chunk before which wasn't rendering my markdown file properly so I simply reverted it back. I'm wondering if these sort of updates can be made after the deadline though? Since I have my .MD file ready to pushed to github.

Thanks!

Zeid H

**Comment by zjbthomas** [comment]
Hi @zeeva85,
I think it doesn't matter whether you use `TRUE` or `true` (and `True` is not valid in YAML). May I know if you can generate a proper MD file for GitHub, with tables created by `knitr::kable()`? Thank you.

**Comment by zeeva85** [comment]
hey @zjbthomas, what I meant, sometime for some reason the syntax is not highlighted the YAML on my documents and when that happens it prints or it does funny things instead of evaluating it, I have had that happen in the past, not sure why, so I make sure the syntax is always highlighted and I take it as a text if its not highlighted properly..

Yes, my markdown does a kable generated table properly I guess, not sure if what you meant by properly rendered but here is the link to my markdown with knirt::kable in action, hopefully thats what you were after.

[link](https://github.com/STAT545-UBC-students/hw02-zeeva85)
