### ISSUE TITLE
Any cleaner way to do practise question 2?

### ISSUE THREAD

**Issue by ntjjmak** [STAT545-UBC/Discussion-Internal#34]
Hi guys,

Just wondering if I can compare answers to practise question 2 (or others if you wish to add!) found at the end of the class exercise document cm008.

I have: 

**Compute the change in population from 1962 to 1972 for each country.**

```r
gapminder %>%

group_by(continent, country) %>%

filter(year>1961, year<1973) %>%

mutate(change_in_pop = pop-lag(pop))``

Look forward to your suggestions!

**Comment by bassamjaved** [comment]
I did the following:

gapminder %>% 
  group_by(country) %>% 
  mutate(delta = pop[year == 1972] - pop[year == 1962]) %>% 
  distinct(delta)

**Comment by rachlobay** [comment]
This reminded me of the question in cm008 under the mutate section that said "How about growth compared to `1972`?" Hence, my solution closely follows the solution for that in-class problem. The only pat that I changed was inside the mutate part of the solution. I simply changed the first pop to pop[year == 1972] and the year after the subtraction to 1962 instead of 1972, which was originally there.

So, my solution is  basically what @bassamjaved wrote except I didn't have the distinct() part at the end.
