### ISSUE TITLE
HW4 Clarification

### ISSUE THREAD

**Issue by schignel** [STAT545-UBC/Discussion-Internal#38]
Hi @vincenzocoia , 

I am wondering if you could quickly clarify the instructions for [HW4](http://stat545.com/Classroom/assignments/hw04/hw04.html): 

In the Assignment Instructions, when asking us to choose one "Prompt", do you mean for us to choose one of the Activities listed under each Prompts heading, or do you mean for us to do all of the Activities under each Prompts heading? I'm guessing it's the former, but just wanted to double check. 

Thank you!
Steve

**Comment by j-schaub** [comment]
@schignel 
Hi Steve,

From the assignment:

"This is a “choose your own adventure”-style assignment, where you are expected to do the following **two** things:

1. Pick **one** of the data reshaping prompts and do it.
2. Pick **one** of the join prompts and do it."

I took that to mean we had to choose one activity from each type, otherwise it would be more than two things. Hope this helps!

Jessica

**Comment by vincenzocoia** [comment]
You're only expected to do one activity from each section.

**Comment by schignel** [comment]
Thanks to both of you!

**Comment by rasiimwe** [comment]
@vincenzocoia, @j-schaub 
Thanks for the clarity
