### ISSUE TITLE
Rendering large html files on GitHub

### ISSUE THREAD

**Issue by rasiimwe** [STAT545-UBC/Discussion-Internal#46]
@vincenzocoia @Rashedul  @sherrie9 @ChadFibke 

I have an rmd file with a few plotly plots that I would like to knit to html for my plotly plots to be rendered.

Commiting staged file changes is successful with the warning  `the diff is extremely large & may cause Rstudio to slow down or even hang`

**On github:** The file can't be rendered because it's large 👇 

`View Raw`
`(Sorry about that, but we can’t show files that are this big right now.)`

👉 How best can such large html files be rendered on github?

Thanks

**Comment by ShuxianFan** [comment]
Try out the RawGit website.

**Comment by zjbthomas** [comment]
Also for assignment 5, I figure out when using `ggplotly()`, it will show the following error:

> Error: Functions that produce HTML output found in document targeting gfm-ascii_identifiers output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:
always_allow_html: yes
Note however that the HTML output will not be visible in non-HTML formats.

So I think output as HTML will be better for this assignment.

Hi @vincenzocoia , I just discussed with one of the TAs, and he/she said only MD file will be marked. So I just want to know is it possible to use HTML as final submission instead of MD file, considering there is an issue? Or if there is any alternative to solve it. Thank you.

Hi @ShuxianFan , [RawGit](https://rawgit.com/) has reached its end. I found two altenatives to it:

- [HTML Preview](https://htmlpreview.github.io/): more popular and easy to use but it needs time to refreash the cache and show latest content.
- [GitHack](https://raw.githack.com/): similar to RawGit but not sure if it is stable.

Thank you.

**Comment by zeeva85** [comment]
Could try this;-

https://www.finex.co/how-to-display-html-in-github/

**Comment by rasiimwe** [comment]
Thanks @vincenzocoia 

I will give git LFS a try as well.

Many thanks!

**Comment by MielleM** [comment]
Hi @vincenzocoia 

Apologies if I misunderstood, but are the TAs still only marking .mds? 

Like @zjbthomas ,  I was prompted to switch my output to an html_document for plotly to work-- so I don't have an .md to submit.

**Comment by glenn-mcguinness** [comment]
I tried to use the [suggestion](https://www.finex.co/how-to-display-html-in-github/) that @zeeva85 like @rasiimwe, but I encountered a problem when I found that I did not have administrator rights to the repository that Github Classroom created.

@vincenzocoia, what is the recommended method for displaying the html files that we need to submit for this assignment?

**Comment by MielleM** [comment]
Thanks, @vincenzocoia!
