### ISSUE TITLE
Bash references

### ISSUE THREAD

**Issue by ecool50** [STAT545-UBC/Discussion-Internal#5]
Here are some useful link(s) for getting started with bash on windows and some of its commands.

Install bash on windows: https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

Useful commands: https://courses.cs.washington.edu/courses/cse390a/14au/bash.html

**Comment by rasiimwe** [comment]
Thanks @ecool50 for your post.

Depending on the environment someone is using, they may not need to install linux bash for windows  unless one is really interested in using this option/ for future interest. The terminal comes inbuilt in most operating systems however some of the commands used in linux are different from those used in windows. 

For example:
Instead of **"ls"** for "list files in working directory" when using a Mac or linux. --> use **"dir"** in windows
**"cd"** (alone) in windows can also work as linux's **"pwd"** 
(Commands that work for your environment can be found online)

Apart from R, the terminal/command prompt can be accessed through:
**"All Programs" > "Accessories" > "Command Prompt"** or 
**Run > type "cmd"** in windows
(please check online for more helpful avenues including shortcuts!)

Also, depending on your environment and task at hand, you may find it helpful to run the terminal as an administrator or to run R as an administrator for some packages to be installed.

Hope this helps :blush:

**Comment by zeeva85** [comment]
I have this unix/linux cheatsheet pasted on the wall at my desk, hope it helps.

[cheat sheet](https://files.fosswire.com/2007/08/fwunixref.pdf)

Cheers 🍻
