### ISSUE TITLE
Markdown editor 

### ISSUE THREAD

**Issue by zuhengxu** [STAT545-UBC/Discussion-Internal#6]
Here are two markdown editors I am using, supporting live preview.
You don't have to click the preview button to see the outcomes.

MacDown for OSX:
http://macdown.uranusjr.com

Typora for windows:
https://typora.io

**Comment by zuhengxu** [comment]
MacDown:
<img width="1101" alt="screen shot 2018-09-06 at 1 56 44 pm" src="https://user-images.githubusercontent.com/42751767/45184841-04219a80-b1dd-11e8-9563-7d8564dd238c.png">

Typora:
<img width="658" alt="screen shot 2018-09-06 at 1 58 33 pm" src="https://user-images.githubusercontent.com/42751767/45184861-0f74c600-b1dd-11e8-9413-ec78d4744324.png">

**Comment by rasiimwe** [comment]
Nice! Thanks for sharing @zuhengxu

**Comment by rachlobay** [comment]
Thanks for the recommendation @zuhengxu. I want to put forward Ghostwriter because it is an open-source and cross-platform markdown editor. As with your recommendations, Ghostwriter has live preview capability. You can check it out on GitHub: [https://github.com/wereturtle/ghostwriter](https://github.com/wereturtle/ghostwriter)
