### ISSUE TITLE
Getting TA help in class

### ISSUE THREAD

**Issue by vincenzocoia** [STAT545-UBC/Discussion-Internal#9]
Does anyone have ideas as to how students can better utilize the help of TA's during class? Here are a few ideas the @STAT545-UBC/2018_teaching_team came up with so far. We'd be happy to hear comments and/or ideas from @STAT545-UBC/2018_students! 

- Hand out "sticky notes" for students to put on their laptops when they want some assistance.
- Take a mini break every 15 or so minutes to turn the table to TA questions.
- Use an online service like Slack, where students can post questions (and somehow simultaneously identify where they are sitting in the classroom).
- TA's try to be more mobile during class, making it easier to help by proximity (despite the theatre-style layout of the room!)

**Comment by rachlobay** [comment]
- Out of the options that are listed above, I like the take a mini break every 15 minutes or so to turn the table to TA questions. I think that method is good because students who get stuck on one concept or coding exercise will get the help they need pretty quickly. This is important because lecture material often build on material that was introduced earlier. So, if somebody gets stuck early on and they don't ask for help, they may still be stuck later on in the lecture. However, the mini break method may disrupt the flow of the lecture.

- The online service option may be good, but sounds like it would take some work to set up. A plus for this method is that it probably would not disrupt the flow of the class as much as the mini break option.

- The sticky note method could also work, but it may be difficult for TAs to see the sticky notes on their laptop unless the TA's have a good vantage point. 

My idea is to use a simple hand system. An open and fully raised hand means that the student has a question for the lecturer, while a thumbs up or peace sign that is around laptop screen level (or a raised pencil... something like that) means that TA help is needed. TAs may have to move around to see the help signals during class. I think that this method would be easy to implement because it doesn't require any additional supplies. However, this method may be confusing if the students are far away and it is not easy for the lecturer to discern if they have a full hand up or not. So... it may not be the best method when we look at all the methods, but it may be worth a shot.

I am interested to see what other students think.

**Comment by Caroline-Seip** [comment]
I didn't find the 10 minute break to be very helpful, preferred to just flag the TAs as we worked through exercises. I did find that having the TAs more mobile around the classroom worked well for getting their attention

**Comment by vincenzocoia** [comment]
Thanks for the feedback, @Caroline-Seip! Let's take the temperature here:

@STAT545-UBC/2018_students Please add a reaction to this post: did you find the 10-minute break useful?

- Thumbs up 👍  = I found the 10 minute break helpful
- "Confused" face 😕 = neutral
- Thumbs down 👎 = I did NOT find the 10 minute break helpful

**Comment by bassamjaved** [comment]
👍

**Comment by fjbasedow** [comment]
😕

**Comment by ericjsanders** [comment]
@bassamjaved @fjbasedow if you're on the browser looking at a GitHub issue, you should see a smiley icon on the top right of any comments that let's you actually react to the comment just like reacting to things on Facebook :) That way people don't all have to reply with whole emoticon comments.

**Comment by schignel** [comment]
I thought the break was very helpful, and allowed me to catch up on and review a couple of steps that I hadn't quite understood.  It might even be more effective if there was a 5 minute break roughly half way through the class, and then another 5 minutes break at the end.

**Comment by seraphinearnold** [comment]
I found the break very useful to catch up to the lecture again, because I struggeld with installing/configurating GitHub. Even though the TAs were busy at that moment, I could solve my problems with the help of a kind classmate who sat beside me :)

**Comment by tsmith93** [comment]
I agree with the past three comments. The break was useful. Being very new to GitHub and RStudio, the class can feel very overwhelming if you miss a step for whatever reason. The break allowed me to catch up on anything missed and for a bit of a mental reset. Though, the break could probably be shortened by several minutes.

**Comment by couBC** [comment]
👍

**Comment by ShuxianFan** [comment]
👍

**Comment by zeeva85** [comment]
👍  that the break was useful, sometimes the laptop does these peculiar little things that divide my attention when I should be paying attention on the lecture, the break gave me the much needed time to catch up on those moments.

**Comment by Bill1111** [comment]
Something that I think would be very helpful is if Dr. Coia recorded his screen and audio using quicktime. As someone who is new to GIthub, I often find that I miss a step and then am completely lost. Or I do it in class, but then completely forget how to do it when I get home. A recording would be extremely helpful to be able to go back to for reference. Just an idea :)

**Comment by xcct2012** [comment]
👍
