### ISSUE TITLE
hw10 release date

### ISSUE THREAD

**Issue by Caroline-Seip** [STAT545-UBC/Discussion-Internal#91]
Hey @STAT545-UBC/2018_teaching_team 

Just wondering when hw10 will be released. I think a lot of us are leaving town on Friday after classes finish so I was hoping we could see what the assignment looks like and have at least one office hour available- thanks!

**Comment by vincenzocoia** [comment]
@STAT545-UBC/2018_students I think this is a good thread to make this announcement.

Because of the deadline being further in December, and because I'm getting the sense that the workload for this course is quite high, __Homework 10 and Peer Review 10 is now optional__. 

What this means: We'll take the top 4 assignment grades, and make those worth 75% of your final mark. Same with your peer reviews: we'll take the top 4 peer reviews. I'll update the syllabus shortly.

Also, I'll be posting hw10 sometime today.

**Comment by zjbthomas** [comment]
Hi @vincenzocoia thanks for the clarification! In this case, is it possible to speed up marking of all previous assignments so we can make our final decision on whether we need to do homework 10 or not? Thank you.
